import ToastProvider from '@/components/feedback/ToastProvider';
import type { Metadata } from 'next';
import '@/styles/global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full w-full'>
      <body className='h-full w-full antialiased'>
        <main className='h-full w-full'>{children}</main>

        <ToastProvider />
      </body>
    </html>
  );
}
